services:
  weather-bff:
    build:
      context: ./weather-bff
    container_name: weather-bff
    ports:
      - "8081:8080"
    networks:
      - weather-net
    depends_on:
      - weather-service
    env_file:
      - ./weather-bff/.env

  weather-service:
    build:
      context: ./weather-service
    container_name: weather-service
    networks:
      - weather-net
    env_file:
      - ./weather-service/.env

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - weather-net

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
    networks:
      - weather-net
    depends_on:
      - zipkin

networks:
  weather-net:
    driver: bridge
