services:
  weather-bff:
    build:
      context: ./weather-bff
    container_name: weather-bff
    ports:
      - "8081:8080"
    networks:
      - weather-net
    depends_on:
      - weather-service
    env_file:
      - ./weather-bff/.env

  weather-service:
    build:
      context: ./weather-service
    container_name: weather-service
    networks:
      - weather-net
    env_file:
      - ./weather-service/.env

networks:
  weather-net:
    driver: bridge
