services:
  bff:
    build:
      context: ./weather-bff
    container_name: weather-bff
    ports:
      - "8081:8080"
    networks:
      - weather-net
    depends_on:
      - service

  service:
    build:
      context: ./weather-service
    container_name: weather-service
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge
